apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-caller-config
data:
  SPRING_APPLICATION_NAME: hello-caller
  SERVER_PORT: "8080"
  HELLO_SERVICE_URL: "http://hello-service:8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always" 